site_name: Pylearner
nav:
    - Home: README.md
    - Políticas:
        - policies/Branches.md
        - policies/Commits.md
        - Definição de Done: policies/Definicao-Done.md
        - policies/Git-Workflow.md
        - policies/Style-Guide.md
    - Documentação:
        - Documento de Arquitetura: documentation-mds/Documento-de-Arquitetura.md
        - Documento de Visão: documentation-mds/Documento-de-Visao.md
        - Documento de Metodologia: documentation-mds/Documento-de-Metodologia.md
        - TAP: Tap.md
        - EAP: Eap.md
        - Backlog: Backlog.md
    - Roadmaps:
        - roadmap/Roadmap-TechLead.md
        - roadmap/Roadmap-DevOps.md
        - roadmap/Roadmap-Arquiteto.md
        - roadmap/Roadmap-Projeto.md
    - Documentação das sprints:
        - Sprint 0 Review: sprints/Sprint-0-review.md
        - Sprint 1 Planning: sprints/Sprint-1-planning.md
        - Sprint 1 Review: sprints/Sprint-1-Review.md
        - Sprint 2 Planning: sprints/Sprint-2-planning.md
        - Sprint 2 Review: sprints/Sprint-2-review.md
        - Sprint 3 Planning: sprints/Sprint-3-planning.md
        - Sprint 3 Review: sprints/Sprint-3-review.md
        - Sprint 4 Planning: sprints/Sprint-4-planning.md
        - Sprint 4 Review: sprints/Sprint-4-review.md
        - Sprint 5 Planning: sprints/Sprint-5-planning.md
        - Sprint 5 Review: sprints/Sprint-5-review.md
        - Sprint 6 Planning: sprints/Sprint-6-planning.md
        - Sprint 6 Review: sprints/Sprint-6-review.md
        - Sprint 7 Planning: sprints/Sprint-7-planning.md
        - Sprint 7 Review: sprints/Sprint-7-review.md
        - Sprint 8 Planning: sprints/Sprint-8-planning.md
        # Sprint 8 Review: sprints/Sprint-8-review.md
        # Sprint 9 Planning: sprints/Sprint-9-planning.md
        # Sprint 9 Review: sprints/Sprint-9-review.md
        # Sprint 10 Planning: sprints/Sprint-10-planning.md
        # Sprint 10 Review: sprints/Sprint-10-review.md
        # Sprint 11 Planning: sprints/Sprint-11-planning.md
        # Sprint 11 Review: sprints/Sprint-11-review.md
        # Sprint 12 Planning: sprints/Sprint-12-planning.md
        # Sprint 12 Review: sprints/Sprint-12-review.md
        # Sprint 13 Planning: sprints/Sprint-13-planning.md
        # Sprint 13 Review: sprints/Sprint-13-review.md
    - Documentação do Estudo:
        - documentation-mds/Documento-da-US01.md
        - documentation-mds/Documento-da-US02.md
        - documentation-mds/Documento-da-US03.md
        - documentation-mds/Documento-da-US04.md
        - documentation-mds/Documento-da-US05.md
        - documentation-mds/Documento-da-US06.md
        - documentation-mds/Documento-da-US07.md
        - documentation-mds/Documento-da-US08.md
        - documentation-mds/Documento-da-US09.md
        - documentation-mds/Documento-da-US10.md
        - documentation-mds/Documento-da-US11.md
        - documentation-mds/Documento-da-US14.md
        - documentation-mds/Documento-da-US15.md
        - documentation-mds/Documento-da-US16.md
        - documentation-mds/Documento-da-US17.md
theme:
  name: readthedocs
extra_css:
    - css/extra.css
