site_name: Pylearner 
nav:
    - Home: README.md
    - Documento de Arquitetura: documentation/Documento-de-Arquitetura.md
    - Documento de Visão: documentation/Documento-de-Visao.md
    - Documento de Metodologia: documentation/Documento-de-Metodologia.md
    - TAP: Tap.md
    - EAP: Eap.md
    - Documentação das sprints: 
        - sprints/Sprint-0-review.md
        - sprints/Sprint-1-Review.md
        - sprints/Sprint-1-planning.md
        - sprints/Sprint-2-planning.md
        - sprints/Sprint-2-review.md
        - sprints/Sprint-3-planning.md
    - Roadmaps Individuais:
        - roadmap/Roadmap-TechLead.md
        - roadmap/Roadmap-DevOps.md
        - roadmap/Roadmap-Arquiteto.md
theme:
  name: 'rtd-dropdown'
extra_css:
    - css/extra.css
