site_name: Pylearner 
nav:
    - Home: README.md
    - Políticas:
        - policies/Branches.md
        - policies/Commits.md
        - policies/Definicao-Done.md
        - policies/Git-Workflow.md
        - policies/Style-Guide.md
    - Documentação:
        - Documento de Arquitetura: documentation-mds/Documento-de-Arquitetura.md
        - Documento de Visão: documentation-mds/Documento-de-Visao.md
        - Documento de Metodologia: documentation-mds/Documento-de-Metodologia.md
        - TAP: Tap.md
        - EAP: Eap.md
        - Backlog: Backlog.md
    - Roadmaps:
        - roadmap/Roadmap-TechLead.md
        - roadmap/Roadmap-DevOps.md
        - roadmap/Roadmap-Arquiteto.md
        - roadmap/Roadmap-Projeto.md
    - Documentação das sprints: 
        - sprints/Sprint-0-review.md
        - sprints/Sprint-1-planning.md
        - sprints/Sprint-1-Review.md  
        - sprints/Sprint-2-planning.md
        - sprints/Sprint-2-review.md
        - sprints/Sprint-3-planning.md
        - sprints/Sprint-3-review.md
        - sprints/Sprint-4-planning.md
        - sprints/Sprint-4-review.md
        - sprints/Sprint-5-planning.md
        - sprints/Sprint-5-review.md
        - sprints/Sprint-6-planning.md
        # - sprints/Sprint-6-review.md
        # - sprints/Sprint-7-planning.md
        # - sprints/Sprint-7-review.md
        # - sprints/Sprint-8-planning.md
        # - sprints/Sprint-8-review.md
        # - sprints/Sprint-9-planning.md
        # - sprints/Sprint-9-review.md
        # - sprints/Sprint-10-planning.md
        # - sprints/Sprint-10-review.md
        # - sprints/Sprint-11-planning.md
        # - sprints/Sprint-11-review.md
        # - sprints/Sprint-12-planning.md
        # - sprints/Sprint-12-review.md
        # - sprints/Sprint-13-planning.md
        # - sprints/Sprint-13-review.md
    - Documentação do Estudo: 
        - documentation-mds/Documento-da-US01.md
        - documentation-mds/Documento-da-US02.md
        - documentation-mds/Documento-da-US03.md
        - documentation-mds/Documento-da-US04.md
        - documentation-mds/Documento-da-US05.md
        - documentation-mds/Documento-da-US14.md
        - documentation-mds/Documento-da-US15.md
        - documentation-mds/Documento-da-US16.md
            
theme:
  name: readthedocs
extra_css:
    - css/extra.css
